### ISSUE TITLE
[BUG]: Can't execute commands without aliases

### ISSUE THREAD

**Issue by nickmccurdy** [github/gh-copilot#44]
### What happened?
`gh copilot suggest` has an `Execute command` option, which does not execute commands since you're not running `ghcs`.

This means shells that don't support aliases like Fish can't be used to execute commands.

### Versions
gh version 2.46.0 (2024-03-20)

### Relevant terminal output
```
? Select an option
> Execute command

Without using the `ghcs` alias or `-s,--shell-out` flag, the suggested command will be copied to your clipboard for you to paste and execute.

Command copied to clipboard!
```

**Comment by hazem3443** [comment]
you need to specify the option ``` -s=/bin/bash ``` to make the copilot know about your bash runner whether it is a **bash** or **sh** or **busy box link** file or anything else so you can give this another try

``` gh copilot suggest --shel-out=/bin/sh ```

**Comment by andyfeller** [comment]
@nickmccurdy : thank you for opening up this issue! 🙇  technically, these aren't aliases in the other shells but I get your point.  Truthfully, I'd like to take another pass at native support for executing these commands rather than using the alias/function wrapper trick.

@hazem3443 : actually, we don't intend users to fiddle with the `-s, --shell-out` flag as that is not what it is intended for.  As I was mentioning in #43, I'd like to remove the mention of `-s,--shell-out` all together from that error message.
